#!/bin/sh

set -e

USER=$(id -un)
HOST=$(uname -n)
PS4="$USER@$HOST~# "

ARCH=${ARCH:-native}
CC=${CC:-cc}

FLAGS="-std=gnu23 \
-march=$ARCH \
-O3 \
-flto=auto \
-D_FORTIFY_SOURCE=3 \
-fno-plt \
-fstack-protector-strong \
-fPIE \
-fomit-frame-pointer \
-finline-functions \
-fexceptions"

LFLAGS="-pie \
-flto=auto \
-Wl,-z,relro \
-Wl,-z,now"

echo "[*] Setting up build directory"
set -x
rm -rf out
mkdir -p out
{ set +x; } 2>/dev/null

echo "[*] Building Glass..."
set -x
$CC $FLAGS -o out/glass glass.c -lX11 $LFLAGS
{ set +x; } 2>/dev/null

echo "[*] Building Glass Desktop (glassdesktop)..."
set -x
$CC $FLAGS -o out/glassdesktop glassdesktop.c -lX11 $LFLAGS
{ set +x; } 2>/dev/null


echo "[*] Building glassbg..."
set -x
$CC $FLAGS -o out/glassbg glassbg.c -lImlib2 -lX11 $LFLAGS
{ set +x; } 2>/dev/null

echo "[*] Building glassconfig..."
set -x
$CC $FLAGS -o out/glassconfig glassconfig.c -lX11 -lncurses $LFLAGS
{ set +x; } 2>/dev/null

echo "[✓] Build OK"
